media:
  - label: Images
    name: images
    input: public/images
    output: /public/images
    categories: [ image ]
  - label: Files
    name: files
    input: public/files
    output: files
content: 
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ coverImage, title, date ]
    fields:
      - name: fileName
        label: File name
        type: string
        required: true
      - name: category
        label: Category
        type: select
        required: true
        options:
          values: [Tấm ốp, Phụ kiện nam châm, Kinh nghiệm nội thất]
      - name: subCategory
        label: Sub Category
        required: true
        type: select
        options:
          multiple: true
          values: [Tấm ốp thép tráng men, Tấm ốp tường vân đá, Phụ kiện bếp, Nội thất hay]          
      - { name: title, label: Title, type: string, required: true }
      - { name: excerpt, label: Description, type: string, required: true }
      - name: coverImage
        label: Cover image
        type: object
        required: true
        fields:
          - { name: coverImage, label: Cover image, type: image, required: true }
          - { name: coverImageAlt, label: Cover image alt, type: string, required: true }
      - { name: date, label: Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string, required: true }
          - { name: picture, label: Picture, type: image, required: true }
      - name: ogImage
        label: Image (social sharing)
        type: object
        fields:
          - { name: url, label: URL, type: image }
      - { name: body, label: Body, type: rich-text }
      - name: isReadyForPublish
        label: Publish
        type: boolean
        required: true  
    filename: '{fields.fileName}.md'