media:
  input: public/assets
  output: /assets
  categories: [ "image" ]
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ coverImage, title, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
    filename: '{fields.title}.md'