steps:
  - name: "gcr.io/cloud-builders/docker"
    id: build-docker-image
    args: ["build", "-t", "gcr.io/$PROJECT_ID/kurashi-frontpage-prod-$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    waitFor: ["build-docker-image"]
    args: ["push", "gcr.io/$PROJECT_ID/kurashi-frontpage-prod-$SHORT_SHA"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: deploy-to-cloudrun
    entrypoint: gcloud
    args:
      - "run"
      - "services"
      - "update"
      - "kurashi-frontpage"
      - "--image"
      - "gcr.io/$PROJECT_ID/kurashi-frontpage-prod-$SHORT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--labels"
      - "managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$SHORT_SHA,gcb-build-id=$BUILD_ID"
options:
  logging: CLOUD_LOGGING_ONLY    
timeout: "1800s"