steps:
  - name: "node:18"
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - 'DATABASE_URL=${_DATABASE_URL}'
      - 'SITE_URL=${_SITE_URL}'
  - id: install-proxy
    name: 'gcr.io/cloud-builders/wget'
    entrypoint: bash
    args:
      - "-c"
      - "wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.1/cloud-sql-proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy"
  - id: migrate
    waitFor: ['install-proxy']
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: sh
    args:
      - "-c"
      - "(./cloud_sql_proxy kurashi-frontpage-419616:us-central1:kurashi-production-db & sleep 2) && npm run db:deploy"
    timeout: '1200s'
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/kurashi-frontpage-prod:$COMMIT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/kurashi-frontpage-prod:$COMMIT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "kurashi-frontpage-prod:$COMMIT_SHA"
      - "--image"
      - "gcr.io/$PROJECT_ID/kurashi-frontpage-prod:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"   
options:
  logging: CLOUD_LOGGING_ONLY    
timeout: "1800s"