export const metadata = {
  title: 'Home',
  description: 'Generated by Next.js'
}

const RootLayout = ({ children }: { children: React.ReactNode }): React.ReactElement => {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
