export { default as LogoYoutube } from '@/components/svg-icons/youtube'
export { default as LogoFacebook } from '@/components/svg-icons/facebook'
export { default as LogoZalo } from '@/components/svg-icons/zalo'
export { default as LinkIcon } from '@/components/svg-icons/link'
export { default as ShoppingCart } from '@/components/svg-icons/shopping-cart'
export { default as ColorIcon } from '@/components/svg-icons/color'
export { default as PriceIcon } from '@/components/svg-icons/price-icon'
